# This is project specific rubocop configuration file.
# You can tweak project settings here
inherit_from:
  - ./.rubocop.localch.yml

Lint/IneffectiveAccessModifier:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Rails/OutputSafety:
  Enabled: false
