# This is project specific rubocop configuration file.
# You can tweak project settings here
inherit_from:
  - ./.rubocop.localch.yml

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Style/SignalException:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Naming/PredicateName:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
