FROM ruby:2.6.2-alpine

RUN apk --update --upgrade --no-cache add build-base nodejs libxml2-dev libxslt-dev tzdata git bash linux-headers

RUN mkdir /gem
WORKDIR /gem
ENV RAILS_ENV test

ADD . /gem

RUN bundle config --global build.nokogiri  "--use-system-libraries" && \
    bundle install -j4
